# Generated by Django 5.0 on 2023-12-22 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_post_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter_id", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_matches", models.JSONField()),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("tone_analysis", models.JSONField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.coverletter",
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimized_content", models.TextField()),
                ("optimized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="optimizers.analysis",
                    ),
                ),
                (
                    "original_cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_cover_letter",
                        to="optimizers.coverletter",
                    ),
                ),
                (
                    "original_job_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_job_post",
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_id", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_matches", models.JSONField()),
                ("complexity_score", models.FloatField(blank=True, null=True)),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("section_feedback", models.JSONField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimized_content", models.TextField()),
                ("optimized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.resume",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="optimizers.resumeanalysis",
                    ),
                ),
            ],
        ),
    ]
