# Generated by Django 5.0 on 2024-01-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimizers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optimizedcontent",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="optimizedcontent",
            name="original_cover_letter",
        ),
        migrations.RemoveField(
            model_name="optimizedcontent",
            name="original_job_post",
        ),
        migrations.RenameField(
            model_name="optimizedresume",
            old_name="original_resume",
            new_name="resume",
        ),
        migrations.RenameField(
            model_name="resumeanalysis",
            old_name="complexity_score",
            new_name="sentiment_score",
        ),
        migrations.RemoveField(
            model_name="coverletter",
            name="content",
        ),
        migrations.RemoveField(
            model_name="coverletter",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="coverletter",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="content",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="job_post",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="section_feedback",
        ),
        migrations.AddField(
            model_name="coverletter",
            name="general_improved_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="general_improved_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="cover_letters/general_improved/"
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="original_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="cover_letters/original/"
            ),
        ),
        migrations.AddField(
            model_name="optimizedresume",
            name="is_tailored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="optimizedresume",
            name="optimized_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/optimized/"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="general_improved_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="general_improved_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/general_improved/"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="original_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/original/"
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="tone_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="keyword_matches",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CoverLetterAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("tone_analysis", models.JSONField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("keyword_matches", models.JSONField(blank=True, null=True)),
                (
                    "cover_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.coverletter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobPostAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("tone_analysis", models.JSONField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptimizedCoverLetterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimized_content", models.TextField()),
                (
                    "optimized_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="cover_letters/optimized/"
                    ),
                ),
                ("is_tailored", models.BooleanField(default=False)),
                ("optimized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="optimizers.coverletteranalysis",
                    ),
                ),
                (
                    "cover_letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.coverletter",
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedJobPostContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimized_content", models.TextField()),
                ("optimized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="optimizers.jobpostanalysis",
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="optimizers.jobpost",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Analysis",
        ),
        migrations.DeleteModel(
            name="OptimizedContent",
        ),
    ]
