# Generated by Django 5.0 on 2024-02-01 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("optimizers", "0002_remove_optimizedcontent_analysis_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OptimizedResume",
            new_name="OptimizedResumeContent",
        ),
    ]
