# Generated by Django 5.0 on 2024-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimizers", "0003_rename_optimizedresume_optimizedresumecontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="description",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="title",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="optimized_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="OptimizedJobPostContent",
        ),
    ]
