# Generated by Django 5.0 on 2024-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimizers", "0005_optimizedresumecontent_job_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverletter",
            name="general_improved_pdf",
        ),
        migrations.RemoveField(
            model_name="coverletter",
            name="original_pdf",
        ),
        migrations.RemoveField(
            model_name="optimizedcoverlettercontent",
            name="optimized_pdf",
        ),
        migrations.RemoveField(
            model_name="optimizedresumecontent",
            name="optimized_pdf",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="general_improved_pdf",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="original_pdf",
        ),
        migrations.AddField(
            model_name="coverletter",
            name="general_improved_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="original_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="optimizedcoverlettercontent",
            name="optimized_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="optimizedresumecontent",
            name="optimized_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="general_improved_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="original_pdf_s3_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
