# Pull the base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PLAYWRIGHT_BROWSERS_PATH /ms-playwright

# Ensure apt is set up to work with https sources
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends apt-transport-https ca-certificates wget gnupg2
    
# Add Google Chrome's repository key
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    
# Add Google Chrome's repository
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    
# Update apt sources and install dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    openjdk-17-jdk \
    poppler-utils \
    tesseract-ocr \
    google-chrome-stable \
    nodejs

# Install Node.js, npm, and other dependencies
RUN curl -sL https://deb.nodesource.com/setup_21.x | bash - && \
    apt-get install -y nodejs npm && \
    node --version && npm --version

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /code

# Copy project
COPY . /code/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements-slim.txt

# Install Playwright and browsers
RUN npm i -D playwright && npx playwright install

# Optional: Collect static files
# RUN python manage.py collectstatic --noinput

# Run the application
CMD ["daphne", "chatbackend.asgi:application", "--port", "$PORT", "--bind", "0.0.0.0"]
