# Generated by Django 5.0 on 2023-12-12 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationcustomer",
            name="email",
        ),
    ]
