# Generated by Django 5.0 on 2023-12-22 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=100)),
                ("result", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="InterviewTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript_id", models.CharField(max_length=100, unique=True)),
                ("candidate_name", models.CharField(max_length=100)),
                ("interview_date", models.DateField()),
                ("transcript", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CandidateFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.analysis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysis",
            name="transcript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="meeting.interviewtranscript",
            ),
        ),
        migrations.CreateModel(
            name="RecruiterFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meeting.analysis",
                    ),
                ),
            ],
        ),
    ]
