# Generated by Django 5.0 on 2023-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewtranscript",
            name="transcript_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
