# Generated by Django 5.0 on 2023-12-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_conversation_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_id",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True, unique=True
            ),
        ),
    ]
