# Generated by Django 5.0 on 2023-12-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimilarityMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("matrix_file", models.FileField(upload_to="similarity_matrices/")),
                ("job_ids", models.TextField(default="[]")),
                ("candidate_ids", models.TextField(default="[]")),
            ],
        ),
    ]
