name: Judy Backend CI/CD Pipeline (Staging)

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      env:
        # ===========================================================
        # ------------------------- GENERAL ------------------------- 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      
        # ------------------------- SUPERUSER ------------------------- 
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      
        # ------------------------- DATABASE ------------------------- 
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

        # -------------------------- REDIS CONFIG ----------------------------
        REDIS_URL: ${{ secrets.REDIS_URL }}
      
        # ------------------------- CORS ------------------------- 
        CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}
      
        # ------------------------- CSRF ------------------------- 
        CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
        
        # ------------------------- CDN STORAGE ------------------------- 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      
        # ------------------------- TEXT PROCESSING DETAILS -------------------------
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        
        # ------------------------- CDN STORAGE ------------------------- 
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_API_ENV: ${{ secrets.PINECONE_API_ENV }}
        PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
        
        # ------------------------- MONGO DATABASE DETAILS -------------------------
        MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

        # -------------------------- MEETINGS ----------------------------
        FIREFLIES_API_KEY: ${{ secrets.FIREFLIES_API_KEY }}      
        # ===========================================================

      run: |
        python manage.py test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image for Staging
      if: github.ref == 'refs/heads/staging'
      env:
        DOCKER_BUILDKIT: 1
      run: |  
        docker build -t er:staging .
        docker tag er:staging essentialrecruit/judy-staging:latest
        docker push essentialrecruit/judy-staging:latest
        
    - name: Setup SSH Key and Add to Known Hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    
    - name: Decrypt .env.gpg File
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo $GPG_PASSPHRASE | gpg --quiet --batch --yes --decrypt --passphrase-fd 0 --output ./.env ./.env.gpg

    - name: Transfer Repository to Remote Server
      run: rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/judy/
      
    - name: Execute Docker commands on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          
          cd /home/ubuntu/judy/
          
          # Pull the latest image
          docker pull essentialrecruit/judy-staging:latest

          # Ensure scripts are executable (in case they are not already)
          chmod +x install_docker.sh
          chmod +x entrypoint.sh

          # Check if Docker Compose is installed
          if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
            echo "Installing Docker Compose..."
            ./install_docker.sh
            # No need to modify PATH or logout/login; Docker should be immediately usable
          else
            echo "Docker Compose already installed."
          fi
          
          # Run docker commands using Docker Compose plugin syntax
          sudo docker compose down || echo "Docker Compose down failed or not necessary"
          sudo docker compose up -d || echo "Docker Compose up failed"
      
    - name: Setup crontab for Docker cleanup on the server with logging
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Define the cron job command with logging
          CRON_JOB="0 0 * * * /usr/bin/docker system prune -af > /var/log/docker_cleanup.log 2>&1"
          
          # Create a log file and set permissions (if not already exist)
          TOUCH_LOG_CMD="sudo touch /var/log/docker_cleanup.log && sudo chmod 644 /var/log/docker_cleanup.log"
          (crontab -l | grep -q "/var/log/docker_cleanup.log") || (eval "$TOUCH_LOG_CMD")

          # Check if the cleanup cron job already exists
          (crontab -l | grep -q "docker system prune") || (crontab -l 2>/dev/null; echo "$CRON_JOB") | sudo crontab -

          # Ensure the cron service is running
          sudo service cron restart

          # This cron job is scheduled to run at midnight every day, performing a Docker system prune
          # to remove unused Docker objects and logs the output to /var/log/docker_cleanup.log.
